name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test POO
      id: test-poo
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 3
        max-score: 100
        setup-command: python -m unittest
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-POO_RESULTS: "${{steps.test-poo.outputs.result}}"
      with:
        runners: test-poo
